services:
  - type: web
    name: opportunity-engine
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: UPDATE_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: opportunity-engine-db
          property: connectionString

databases:
  - name: opportunity-engine-db
    plan: free
